### ISSUE TITLE
Can't create streams of f32/f64

### ISSUE THREAD

**Issue by dakom** [clinuxrulz/sodium-rust-push-pull#3]
This works:

```
#[wasm_bindgen]
pub fn create_stream_int32(sodium_ctx: *const SodiumCtx) -> *mut StreamSink<i32> { 

    let sodium_ctx = unsafe { &*sodium_ctx };

    let stream: StreamSink<i32> = sodium_ctx.new_stream_sink();
    Box::into_raw(Box::new(stream))
}
```

These do not:
(error is "the trait `frp::core::sodium_rust::sodium::gc::Trace` is not implemented for `f32` [E0277]"

```
#[wasm_bindgen]
pub fn create_stream_float32(sodium_ctx: *const SodiumCtx) -> *mut StreamSink<f32> { 

    let sodium_ctx = unsafe { &*sodium_ctx };

    let stream: StreamSink<f32> = sodium_ctx.new_stream_sink();
    Box::into_raw(Box::new(stream))
}

#[wasm_bindgen]
pub fn create_stream_float64(sodium_ctx: *const SodiumCtx) -> *mut StreamSink<f64> { 

    let sodium_ctx = unsafe { &*sodium_ctx };

    let stream: StreamSink<f64> = sodium_ctx.new_stream_sink();
    Box::into_raw(Box::new(stream))
}
```

**Comment by clinuxrulz** [comment]
I'll add that to my todo. Impl trace/finalize for all primitive types and types provided by the standard runtime. The trait impls are required so that we can send sodium objects through streamsink/cellsink without problems. You can define it yourself for now, here is a sample:

```
impl Trace for u32 {
    fn trace(&self, _f: &mut FnMut(&GcDep)) {}
}

impl Finalize for u32 {}
```

Just do the same for f32 and f64.

Actually might be better done in the library code, as we can not have duplicate impls of traits.

This is the file that needs the additions. If you feel up to it, you can add those there:

https://github.com/SodiumFRP/sodium-rust/blob/master/src/sodium/impl_/gc.rs

**Comment by clinuxrulz** [comment]
Related: https://stackoverflow.com/questions/24340712/providing-an-implementation-when-both-trait-and-type-are-not-in-this-crate

It will have to be done in the library code after all.

**Comment by clinuxrulz** [comment]
Also this repository is discontinued in favor of https://github.com/SodiumFRP/sodium-rust . the implementation there has been switched to this implementation. That way I'll have just one spot to maintain.

**Comment by dakom** [comment]
Cool - I re-filed it over [there](https://github.com/SodiumFRP/sodium-rust/issues/33)... feel free to close this :)
